# -*- coding: utf-8 -*-
"""Ravi_Naga_Yaswanth.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1zmAa7OxquYgeN8keW7uVlpCuPPfA_4V7

# New Section
"""

import pandas as pd
import numpy as np

input = pd.read_excel("Input_1.xlsx")
print(input)

output = pd.DataFrame(columns= ['Name','Username','Chapter Tag','Test_Name','answered','correct','score','skipped','Time_Taken','Wrong'])

input.iloc[:]



print(len(input.iloc[0,:]))

"""this code can run for any number of tests but the only this test names should be entered"""

name = [0]*len(input.iloc[0,:])
name[3:len(input.iloc[0,:]):6] =["Concept Test 1","Concept Test 2","Concept Test 3","Concept Test 4","Topic Test 1","Concept Test 5","Topic Test 2","Full Test 1","Full test 2"]
print(name[3:56:6])

x = 0
for i in range(len(input.iloc[:])):
  for j in range(3,56,6):
    if input.iat[i,j] != '-':
      output.loc[len(output.index)] = [input.iat[i,0],input.iat[i,1],input.iat[i,2],name[j],input.iat[i,j+2],input.iat[i,j+3],input.iat[i,j],input.iat[i,j+5],input.iat[i,j+1],input.iat[i,j+4]]





Taskoutput=output.set_index('Name')

datatoexcel = pd.ExcelWriter('Taskoutput.xlsx')
  
# write DataFrame to excel
Taskoutput.to_excel(datatoexcel)
datatoexcel.save()